server:
  port: 8444
spring:
  web:
    resources:
      add-mappings: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SupportTrack?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  data:
    redis:
      host: localhost
      port: 6379
      database: 0


mybatis:
  mapper-locations:
    - classpath:mapper/*.xml

logging:
  level:
    com.yibei.supporttrack: debug

redis:
  database: SupportTrack
  key:
    user: 'user'
    permissionList: 'permissionList'
  expire:
    common: 86400 # 24小时

jwt:
  secret: RvzE27PCvxVFhjyU4y3JTDvQ58GfMuRu
  expiration: 86400 # 24小时
  header: Authorization
  tokenHead: Bearer